### ISSUE TITLE
[Test] Re-introduce no import again test

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#143]
The original e2e tests contained a test to check that we don't re-import a cluster if its been removed from Rancher:

https://github.com/rancher-sandbox/rancher-turtles/blob/main/test/e2e/import_test.go#L106-L117

In the refactor this test was dropped. But we should test this functionality via integration test.

**Comment by Danil-Grigorev** [comment]
This is possible to implement after we have an integration suite to work with. Added #194

**Comment by alexander-demicev** [comment]
We added this test back at some point
