### ISSUE TITLE
[PROPOSAL] Support running in & out of Rancher Manager cluster

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#186]
Create a proposal (i.e. design) to support running Rancher Turtles outside of the Rancher Manager cluster. We want to be able to support having multiple CAPI management clusters reporting back to a single Rancher Manager Cluster.

As part of this lets define the proposal process for Rancher Turtles (including creating the template)

**Comment by richardcase** [comment]
Will feed into #4. This is something we want to have long term but isn't an immediate requirement.

**Comment by alexander-demicev** [comment]
Closing for now, will reopen later
