### ISSUE TITLE
Introduce an integration suite

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#194]
### What would you like to be added (User Story)?

As a developer I’d like to add integration tests for the code I write.

### Detailed Description

While e2e test suite provides extensive set of features to test our functionality in different environments, sometimes it does not make sense to write e2e test to verify a minor functionality change. Due to long execution times and additional set of requirements on the environment, this may make this process cumbersome.

Yet, depending on the use-case, writing a unit test for specific code change can likely be impossible without mocking environment configuration details, like API server behavior, storage backend, etc. Therefore there is a need to introduce integration suite for quick and stable testing.

### Label(s) to be applied

/kind feature

**Comment by alexander-demicev** [comment]
Closing as fixed
