### ISSUE TITLE
CAPZ v1.12.0 failing to provision clusters

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#281]
### Description

After thoroughly debugging the issues with the E2E suite #198, we identify that v1.12.0 is failing to provision clusters. The current environment installs the latest version of the infrastructure providers and it was confirmed that rolling back to 1.11.5 fixed this issue. We should investigate why 1.12.0 is failing and what we can do to address this. Until then, we'll be pinning the Azure infrastructure provider to `v1.11.5`.

**Comment by salasberryfin** [comment]
- [ ] After https://github.com/rancher/turtles/pull/646 is merged, we need to enable back E2E test coverage for CAPZ.

**Comment by kkaempf** [comment]
closing since the bug is fixed, creating a follow-up issue to fix the e2e test
