### ISSUE TITLE
Integrate rancher-turtles with sigstore policy-controller

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#284]
This project will allow us to check that the controllers are using verified image tags from our build pipelines, and prevent installation of unverified workloads in the cluster.

https://github.com/sigstore/policy-controller

- [ ] Ensure the installed operator passes the admission process

Optional:
- [ ] Implement e2e scenario displaying the workflow functionality

**Comment by alexander-demicev** [comment]
Closing it for now
