### ISSUE TITLE
Ability to use Rancher Pod Security Templates

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#310]
### What would you like to be added (User Story)?

As an operator
I would like to use the PSA templates in Rancher
To increase the security og my cluster

### Detailed Description

When importing an RKE2 cluster it would be good if we can support PSA templates: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates

### Anything else you would like to add?

Created based on a slack discussion with @ron1

### Label(s) to be applied

/kind feature

**Comment by alexander-demicev** [comment]
Closing for lack of interest, can be reopened later

**Comment by ron1** [comment]
Hi @alexander-demicev , now that https://github.com/rancher/cluster-api-provider-rke2/pull/474 has been implemented, would it make sense to reconsider reopening this issue?
