### ISSUE TITLE
Prevent deletion of CAPIProviders that are in use

### ISSUE THREAD

**Issue by anmazzotti** [rancher/turtles#376]
### What would you like to be added (User Story)?

As a user I would like to not be able to delete any provider, if there are configured clusters using it. 

### Detailed Description

I would like the deletion of any CAPIProvider to be forbidden, if there are Clusters that are currently using such CAPIProvider.

Accidental deletion of the provider can lead to the deletion of control planes, or bootstrap configs, or infra machines, and it will be hard to recover from that. Better to prevent these kind of accidents.

### Label(s) to be applied

/kind feature

**Comment by richardcase** [comment]
CAPI Operator will not delete CRDs, so it won't delete the cluster.

We may also want the option to allow deletion provider but keep the clusters.

**Comment by richardcase** [comment]
From planning, @salasberryfin raised a good point about how do we handle the scenario where there are CAPI clusters that aren't imported into Rancher?

**Comment by alexander-demicev** [comment]
Closing the issue for now
