### ISSUE TITLE
Add telemetry

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#38]
### What would you like to be added (User Story)?

As a rancher-turtles dev/pm
I want to have telemetry available
So that i can see what the usage of the extension is and what features are used.

### Detailed Description

We need to add telemetry to the project. And it should use the same telemetry mechanism as Rancher so needs to use https://github.com/rancher/telemetry.

This is the implementation of the design from #389 

We have to be careful not to include any PII information.

### Label(s) to be applied

/kind feature

**Comment by alexander-demicev** [comment]
Closing it for now
