### ISSUE TITLE
[E2E] Fix Nightly tests

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#382]
The nightly (i.e. long) e2e tests have been failing for some time now. For example:

https://github.com/rancher-sandbox/rancher-turtles/actions/runs/7880148289

We need to fix them and also remove the usage of ngrok. Lets make the following changes:

- Create an EKS based Rancher Manager cluster
- Use nginx ingress and a AWS LB for the host
- Update the Rancher install to use the AWS LB

We could potentially use eksctl to make the provisioning easier.

This would also require #368 to ensure that we clean up.

**Comment by cpinjani** [comment]
JFYI, for Rancher setup, we have a light-weight implementation in hosted-providers-e2e which uses GCP runner public IP and k3s local cluster: https://github.com/rancher/hosted-providers-e2e/blob/main/Makefile#L66
