### ISSUE TITLE
Support user-provided cluster description

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#385]
### Description

As the `clusters.management.cattle.io` resource will now be supported to represent Rancher Clusters (https://github.com/rancher-sandbox/rancher-turtles/pull/362), the cluster specification includes a `Description` field which is **currently not editable**. Users should be allowed to provide a custom value for this field, which could be done via an annotation on the CAPI cluster.

**Comment by alexander-demicev** [comment]
Closing this issue for now
