### ISSUE TITLE
Publish chart to Rancher Charts repo

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#415]
Update the release process to publish the Rancher Turtles chart to https://github.com/rancher/charts instead of our own chart registry.

We'll need to publish charts for 2.8 and 2.9

**Comment by salasberryfin** [comment]
We're discussing whether we should go for `rancher/charts` or keep a Turtles-specific chart repository in https://github.com/rancher-sandbox/rancher-turtles/pull/426
