### ISSUE TITLE
Remove default installation of kubeadm providers

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#416]
Change the Rancher Turtles chart so:

- [ ] It doesn't install the Kubeadm providers by default
- [ ] Chart value that can be set to true to install the kubeadm providers
- [ ] Updates the questions.yaml to allow easy enabling of the value when installing

**Comment by alexander-demicev** [comment]
https://github.com/rancher/turtles/pull/402

**Comment by alexander-demicev** [comment]
@richardcase in the PR above I removed "kubeadm" completely, do we want expose enabling it though chart values or let users manually create CAPIProvider manifest?

**Comment by richardcase** [comment]
We can follow up on enabling additional providers
