### ISSUE TITLE
Rancher Turtles chart not working if installed into Rancher System project

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#439]
### What steps did you take and what happened?

**Steps:**
- On Rancher manager UI, navigate to local cluster > Apps > Repositories > Add RT repo

- Goto Charts > Apps > search turtles > It will provide option to select project, choose System Project and Install
![image](https://github.com/rancher/turtles/assets/73099870/55ab15ac-08a4-4f81-81a6-3da74c206354)

- After installation, namespaces are placed:
![image](https://github.com/rancher/turtles/assets/73099870/0f7a5b29-0f92-4456-a447-1a966f232fa7)

However, _rancher-turtles-cluster-api-operator_ pod does not comes up:
```
> kubectl logs -n rancher-turtles-system      rancher-turtles-cluster-api-operator-5b79f4f66f-bcwxk
Flag --metrics-bind-addr has been deprecated, Please use --diagnostics-address instead. To continue to servemetrics via http and without authentication/authorization set --insecure-diagnostics as well.
E0321 09:14:22.128264       1 config.go:133] controller-runtime/client/config "msg"="unable to load in-cluster config" "error"="open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory" 
E0321 09:14:22.128323       1 config.go:177] controller-runtime/client/config "msg"="unable to get kubeconfig" "error"="invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"
```

### What did you expect to happen?

- Rancher turtles should be up and running when installed into System project
- If its not supported, we should document this.

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

v0.5.0

### Anything else you would like to add?

**Additional info:**
Rancher turtles works fine when installed into None/Default project

### Label(s) to be applied

/kind bug

**Comment by salasberryfin** [comment]
We decided as a team that this is currently not supported and added a new issue to address this in the documentation https://github.com/rancher/turtles-docs/issues/84 which supersedes this one.
