### ISSUE TITLE
Document RKE2 boostrap provider installation

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#446]
We need to document required steps to install RKE2 bootstrap provider (CAPRKE2) in rancher turtles.
In case it will become default, this documentation is not required for release.

**Comment by furkatgofurov7** [comment]
@Danil-Grigorev is this still valid? When the latest version of RT is installed, it will by default enable CAPRKE2 and that is already covered in docs https://turtles.docs.rancher.com/docs/getting-started/install-rancher-turtles/using_helm#install-rancher-turtles-with-cluster-api-operator-as-a-helm-dependency. Or am I misunderstanding this issue?

**Comment by Danil-Grigorev** [comment]
No, that was the condition. As it is currently installed by default, we can close it.
