### ISSUE TITLE
Validate the import manifest URL / content

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#45]
### What would you like to be added (User Story)?

As a rancher capi extension user
I expected that the import url is validated
So that i am not open to malicious workload injection 

### Detailed Description

Currently we just get the content of the URL [here](https://github.com/rancher-sandbox/rancher-turtles/blob/main/internal/controllers/import_controller.go#L429)...there is no validation.

We need to protect the downstream cluster for deploying malicous code.

We can validate the URL and the payload (i.e. yaml)

### Label(s) to be applied

/kind feature

**Comment by alexander-demicev** [comment]
Closing this issue, we should leverage new strict mode for trusting certs to implement an additional security level
