### ISSUE TITLE
[ADR] `v1.Cluster` to `v3.Cluster` Migration

### ISSUE THREAD

**Issue by kkaempf** [rancher/turtles#475]
### Description

Until now, Turtles releases have used `provisioning.cattle.io` as resource for representing CAPI clusters in Rancher. This means that the controller creates `clusters.provisioning.cattle.io` resource when a CAPI cluster (or the namespace where it exists) is configured to be imported into Rancher.

Users that are already using Turtles will have clusters backed by this import mechanism and, when migrating to the new `clusters.management.cattle.io` resource, we need to make sure that clusters are properly upgraded.

The ADR will need to cover:
- How to migrate clusters: from `provisioning.cattle.io` to `management.cattle.io`.
- User actions: do users need to perform specific actions to migrate?
- Migration tools: do we provide script/tooling to simplify migration?
- Deprecation of current controller: how do we deprecate the existing controller after migration?

#### Terms

`v1.Cluster` is equivalent to `clusters.provisioning.cattle.io`, which is the actual resource that is used to represent clusters.
`v3.Cluster` is equivalent to `clusters.management.cattle.io`, which is the actual resource that is used to represent clusters.

**Comment by mbologna** [comment]
ADR in the May milestone

**Comment by salasberryfin** [comment]
ADR is ready and implementation has started.
