### ISSUE TITLE
Create ClusterGroup for each clusterclass with cluster

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#493]
### What would you like to be added (User Story)?

As an operator
I want a cluster group for all cluster created from the same cluster class
So that i can deploy applications to the clusters

### Detailed Description

It would be good to have a Fleet cluster group created for each ClusterClass where a cluster has been created. We should be able to disable this feature if required (globally or at the clusterclass level).

### Anything else you would like to add?

This has been added to the addon provider for fleet: https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet/pull/11

### Label(s) to be applied

/kind feature

**Comment by Danil-Grigorev** [comment]
This functionality is a part of CAAPF code, and the feature is marked as experimental. Can be used with integration added with #559
