### ISSUE TITLE
[etcdbackup&restore] Add backup&restore CRDs and adjust helm chart values

### ISSUE THREAD

**Issue by furkatgofurov7** [rancher/turtles#496]
Add skeleton for [CRDs](https://github.com/furkatgofurov7/turtles-etcd-restore/tree/main/config/crd/bases), hide them behind the feature gate in helm chart [values](https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/values.yaml#L17-L22) (we can add a new feature gate in values.yaml and introduce a separate template for new CRDs, so that CRDs are only installed when it is enabled)

**Comment by alexander-demicev** [comment]
resolved by https://github.com/rancher/turtles/commit/8b876f39c3b29b003ca78ce760ac0a821a128341
