### ISSUE TITLE
[etcdsnapshot&restore] Add dev tooling and docs

### ISSUE THREAD

**Issue by furkatgofurov7** [rancher/turtles#503]
Add examples [folder](https://github.com/furkatgofurov7/turtles-etcd-restore/tree/main/examples), local dev [script](https://github.com/furkatgofurov7/turtles-etcd-restore/tree/main/scripts) (+Tilt changes) and [documentation](https://github.com/furkatgofurov7/turtles-etcd-restore/blob/main/README.md) for setting up a local environment

**Comment by alexander-demicev** [comment]
closing this for now, we can open less generic issue for future developer setup tasks
