### ISSUE TITLE
[BUG] Additional management v3 cluster created after upgrade

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#583]
**Description:**
Additional management v3 cluster created after upgrade, resulting in failed sequential v3 auto-migration.

### What steps did you take and what happened?
1. Install turtles v0.8.0 (v3 option disabled) and import CAPI cluster

![image](https://github.com/rancher/turtles/assets/73099870/85e43f5f-b6c4-4dec-ad64-478b57ac3f52)

2. Upgrade turtles to latest dev version by keeping settings to default (v3 is auto-enabled to true)

![image](https://github.com/rancher/turtles/assets/73099870/3cc36312-8a40-4915-bea7-f57469d8df62)

3. An additional v3 cluster is created and corresponding v1 cluster 

![image](https://github.com/rancher/turtles/assets/73099870/1dd8a72f-f119-49ce-9418-f8d90e7a7a13)

```
$ kubectl get cluster.provisioning.cattle.io -A
NAMESPACE       NAME            READY   KUBECONFIG
default         cluster1-capi   true    cluster1-capi-kubeconfig
fleet-default   c-7q8g7                 
fleet-local     local           true    local-kubeconfig

$ kubectl get cluster.management.cattle.io -A
NAME           AGE
c-7q8g7        92s
c-m-6tl52brj   7m6s
local          16m
```
4. Update turtles settings and set _managementv3-cluster-migration_ to true and let the operation complete.
The migrated cluster is Unavailable in Rancher. 

![image](https://github.com/rancher/turtles/assets/73099870/d915a3f3-323e-4c96-8c04-50b6032e4778)

```
$ kubectl get cluster.management.cattle.io -A
NAME      AGE
c-7q8g7   6m20s
local     20m

$ kubectl get cluster.provisioning.cattle.io -A
NAMESPACE       NAME      READY   KUBECONFIG
fleet-default   c-7q8g7   true    c-7q8g7-kubeconfig
fleet-local     local     true    local-kubeconfig
```

### What did you expect to happen?

No additional cluster creation after upgrade from v0.8.0

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

Dev version - [d7ecf2b](https://github.com/rancher/turtles/commit/d7ecf2b66c9008a1755af57d31c539feec39ef42)
Rancher - v2.8-head

### Anything else you would like to add?
While upgrade from v0.8.0 if both _managementv3-cluster, managementv3-cluster-migration_ = true, then migration completes successfully.

### Label(s) to be applied

/kind bug

**Comment by furkatgofurov7** [comment]
@cpinjani can you please try the latest version of Turtles and see if this is still the case?

**Comment by cpinjani** [comment]
Validated on v0.9.0, the issue is not occurring. Filed a separate issue for failure on Step 4 (https://github.com/rancher/turtles/issues/588)

Cluster details after upgrade:
```
$ kubectl get cluster.provisioning.cattle.io -A
NAMESPACE     NAME            READY   KUBECONFIG
default       cluster1-capi   true    cluster1-capi-kubeconfig
fleet-local   local           true    local-kubeconfig

$ kubectl get cluster.management.cattle.io -A
NAME           AGE
c-m-2j2gwvd4   14m
local          27m
```

**Comment by furkatgofurov7** [comment]
@cpinjani I am closing this, steps 1-3 are not issue anymore after upgrading to the new release [v0.9.0](https://github.com/rancher/turtles/releases/tag/v0.9.0) and only Step 4 was, but that has a separate issue: #588 

Please re-open if you face the same issue again in the future.

/close
