### ISSUE TITLE
CAPI cluster not getting deleted after fleet repo deletion 

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#590]
### What steps did you take and what happened?

**Note:** 
In case of v1 cluster, the issue is not occurring and cluster gets deleted. Need to check if we support this scenario for v3. 

**Steps:**
- Install turtles/UI extension and import CAPI cluster using fleet & namespace label
- Corresponding v3 cluster gets created in Rancher
- **Disable CAPI Auto-import on namespace from UI or remove auto-import label on namespace from back-end**
- Remove fleet repo and check CAPI cluster deletion status

![image](https://github.com/rancher/turtles/assets/73099870/7b369142-2eb1-494c-864f-7e82b576ebd3)

![image](https://github.com/rancher/turtles/assets/73099870/d9ec0ac1-64f4-4408-a771-4a20defce0e2)

```
$ kubectl get cluster
NAME       PHASE      AGE   VERSION
cluster1   Deleting   63m
```

[logs.tar.gz](https://github.com/user-attachments/files/16107171/logs.tar.gz)

### What did you expect to happen?

CAPI cluster should get deleted after fleet repo deletion 

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

v0.9.0

### Label(s) to be applied

/kind bug

**Comment by furkatgofurov7** [comment]
After the team meeting discussion, we agreed that this is the edge case and we need a note to highlight it in maintenance page of turtles book. I will create a separate issue for that in docs repo, so closing it.
