### ISSUE TITLE
Fleet addon provider doesn't have `ProviderName` set

### ISSUE THREAD

**Issue by thehejik** [rancher/turtles#630]
After installing Turtles Operator v0.10.0 with `Seamless integration with Fleet and CAPI` enabled (installs caapf `v0.3.0`) together with UI extension in Rancher v2.8 there is no `ProviderName` set for `fleet` addon in CAPI/Providers overview page. This field seems to be mandatory when adding a custom provider manually. It probably doesn't have any impact on functionality.

![image](https://github.com/user-attachments/assets/100673da-a6ec-487b-b37b-fbe56e87a568)

### What did you expect to happen?

The `ProviderName` is set for eg. to `fleet` value.

### Label(s) to be applied

/kind bug

**Comment by alexander-demicev** [comment]
@Danil-Grigorev any chance we can introduce custom provider names if fetch config is provided?

**Comment by Danil-Grigorev** [comment]
Not sure I understand the question.

Custom provider naming is possible now, and the table viewed in UI shows providers with custom name. It is determined based on `spec.providerName` being set or not. Missing `spec.providerName` uses `metadata.name` as a source for provider name internally.

The only provider wich has no custom name is the `fleet` addon provider. To address the display issue, I propose to change table representation to use a new `status.providerName` field, which will be populated by controller from either of the sources:
- `metadata.name`
- `spec.providerName` (has higher priority)
