### ISSUE TITLE
E2E: separate turtles upgrade tests from import tests

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/turtles#664]
This test now preventing automatic installation of the correct (latest) `CAPIProvider` version, as the version is inherited from previous installation. It should be running separately, to test independent changes in helm chart upgrade.

**Comment by furkatgofurov7** [comment]
Don't we dump and recreate (BeforeEach/AfterEach) an environment for each suite?

**Comment by Danil-Grigorev** [comment]
It is within the suite test setup logic, where the upgrade is performed. We do recreate environment for each suite, but the environment setup is not clean. It should not be a part of suite, but a test case on its own.
