### ISSUE TITLE
Providers version not being updated with turtles upgrade

### ISSUE THREAD

**Issue by cpinjani** [rancher/turtles#691]
### What steps did you take and what happened?

**Steps:**
- Install turtles v0.10.0 and enable docker, aws, gcp infra providers using capi-ui extension
- Following versions are installed: docker: v1.4.6, aws: v2.3.5, gcp: v1.6.0 (auto-installed with turtles - core: v1.4.6, rke2: v0.4.1, addon: v0.3.1)

![image](https://github.com/user-attachments/assets/d1842e39-c1ea-44ae-ada8-a51a49876f41)

- Upgrade turtles to v0.11.0 and check provider versions, core and rke2 versions are upgraded along with turtles version upgrade and not other providers (core: v1.7.3, rke2: v0.5.0)

![image](https://github.com/user-attachments/assets/dbcd06f8-056b-4530-ae97-8ab774e652ed)

### What did you expect to happen?

Installed CAPI Providers should upgrade if newer version is available, along with turtles upgrade

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

v0.11.0

**Comment by Danil-Grigorev** [comment]
This should be implemented as a part of #742

**Comment by Danil-Grigorev** [comment]
Actually, became a part of #751

**Comment by cpinjani** [comment]
Non-custom providers are auto-upgraded with turtles upgrade to v0.12

![image](https://github.com/user-attachments/assets/8a41e29c-2732-47e6-8040-cc4483f67e02)

**Comment by furkatgofurov7** [comment]
why kubeadm cp/bootstrap versions are not auto-updated to v1.7.3?

**Comment by Danil-Grigorev** [comment]
@furkatgofurov7 What you don’t see here is that the version for one Kubeadm provider is pinned to `v1.4.6`, while the other is unset. The provider with a pinned version has a condition set, and it falls into category of user managed providers (version is managed by user).

If the provider does not have version set, it is automatically updated, which is visible from the screen.

```
  - lastTransitionTime: "2024-09-27T09:15:54Z"
    message: Provider version update available. Current latest is v1.7.3
    reason: UpdateAvailable
    severity: Info
    status: "False"
    type: CheckLatestVersionTime
```

**Comment by furkatgofurov7** [comment]
@Danil-Grigorev I don't see where it is visible that they are pinned, but overall I got the idea, thanks!

**Comment by cpinjani** [comment]
Filed bug to track above issue https://github.com/rancher/turtles/issues/758
