### ISSUE TITLE
Turtle patch release

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/turtles#712]
Changes:
- Support for `images` overrides in `clusterctl.yaml`
- CAPI Operator bump to `v0.13.0`
- `CAPIProvider` deletion fixes
- `rancherInstalled` helm option and cache timeout fixes, in case of no rancher installed.

**Comment by Danil-Grigorev** [comment]
After discussion, this no longer seems to be time sensitive, as an alternative immediate solution was implemented.

**Comment by salasberryfin** [comment]
Is it ok if we close this one @Danil-Grigorev? We'll be releasing a new minor version anyway.

**Comment by Danil-Grigorev** [comment]
Yes, this was here for posterity (re: last comment  https://github.com/rancher/turtles/issues/712#issuecomment-2328887673)
