### ISSUE TITLE
Implement snapshot controller functionality

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/turtles#725]
We now have the skeleton for the controller, we need to implement actual making of snapshots using system-agent

**Comment by Danil-Grigorev** [comment]
As a clarification - actual making of snapshots is meant “user requested” snapshots? Putting a question here as I assumed it is, but reading back it does not look clear to me.

Asking, since automatic snapshot taking functionality is implemented, and performed via RKE2 configuration.
