### ISSUE TITLE
Prime build of CAPRKE2

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/turtles#745]
Currently, CAPRKE2 images are built and pushed to the GitHub image registry because the Sylva project consumes them. We need to think about how we can make prime builds for it.

**Comment by alexander-demicev** [comment]
https://github.com/rancher/cluster-api-provider-rke2/pull/456

**Comment by furkatgofurov7** [comment]
https://github.com/rancher/cluster-api-provider-rke2/pull/473
