### ISSUE TITLE
Release notes generate wrong changelog

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#816]
# Description

When creating a new release, release notes are generated comparing new release to an older version and not the directly previous one, which creates a wrong list of changes.

e.g. automatic release notes for v0.13 used v0.10 as base tag, while it should be compared against v0.12.

**Comment by alexander-demicev** [comment]
This is automated on the github side, the workaround is to remove generated changelog when publishing the release, manually select previous tag and click generate note button
