### ISSUE TITLE
Investigate managed cluster adoption

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#829]
## Description

Cluster adoption is a topic that has been brought up a few times over the last few weeks. Although this is provider-dependent, it would be interesting to test how this works and understand what are the pros/cons of performing this operation.

As a user, I'd like to convert an existing cluster into a CAPI cluster.

## Notes

- CAPZ supports adopting AKS clusters: https://capz.sigs.k8s.io/managed/adopting-clusters

**Comment by alexander-demicev** [comment]
closing it for now, the initial investigation was done:

- it's possible to adopt AKS clusters with CAPZ
- there are gaps like managed network for AKS that are not supported by CAPZ
- we can provide a CLI to generate CAPI manifests for clusters that need to be migrated
- Other providers will need to be tested

We can open more specific issues for future work
